esphome:
  name: esp32-stair-neopixel

esp32:
  board: nodemcu-32s
  framework:
    type: arduino


# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

wifi:
  networks:
  - ssid: !secret IOT_ssid
    password: !secret IOT_password
  - ssid: !secret IOT_alt_ssid
    password: !secret IOT_alt_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Stair-Neopixel"
    password: !secret recovery_password
    
mqtt:
  broker: !secret mqtt_broker
  
light:
  - platform: neopixelbus
    #default_transition_length: 0.5s
    type: GRBW
    variant: SK6812
    pin: GPIO4
    num_leds: 299
    name: "Staircase NeoPixel Light"
    
    effects:
      - random:
          name: Random
          transition_length: 5s
          update_interval: 7s
      
      - flicker:
          name: Flicker
          alpha: 95%
          intensity: 1.5%
          
      - addressable_rainbow:
          name: Rainbow
          speed: 5
          width: 100
          
      - addressable_color_wipe:
          name: Color Wipe
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 10
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 10
          add_led_interval: 100ms
          reverse: false
          
      - addressable_scan:
          name: Scan
          move_interval: 100ms
          scan_width: 1
          
      - addressable_fireworks:
          name: Fireworks
          update_interval: 32ms
          spark_probability: 10%
          use_random_color: false
          fade_out_rate: 120

sensor:
  - platform: internal_temperature
    name: "Internal Temperature"

captive_portal:

    